<!-- wp:group {"tagName":"section","metadata":{"name":"About Us"},"align":"full","style":{"color":{"background":"rgba(255,88,33,0.03)"},"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|50","bottom":"var:preset|spacing|30","left":"var:preset|spacing|50"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":646}},"className":"full-width","layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"}} -->
<section class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,88,33,0.03);min-height:646px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--50)"><!-- wp:columns {"verticalAlignment":null,"align":"wide","style":{"border":{"radius":"0px"},"spacing":{"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"blockGap":{"top":"0px","left":"0px"}},"className":"full-width","customStyle":{"style":""},"layout":{"selfStretch":"fit","flexSize":null}}} -->
<div class="wp-block-columns alignwide" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:column {"width":"","style":{"spacing":{"padding":{"top":"0","bottom":"0"}}}} -->
<div class="wp-block-column" style="padding-top:0;padding-bottom:0"><!-- wp:group {"layout":{"type":"constrained","contentSize":"100%"}} -->
<div class="wp-block-group"><!-- wp:image {"width":"550px","style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"blob-image"} -->
<figure class="wp-block-image is-resized blob-image" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><img src="@asset('images/about.jpg')" alt="" style="width:550px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"53.5%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:53.5%"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"8px","padding":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":526}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:526px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":39}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:39px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"746px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:heading {"textAlign":"left","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"32px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-left full-width has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:32px;font-weight:700;line-height:1.2">About Us</h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":72}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:72px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"746px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"16px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-left full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:16px;font-weight:400;line-height:1.5">Dolor iure expedita id fuga asperiores qui sunt consequatur minima. Quidem voluptas deleniti. Sit quia<br>molestiae quia quas qui magnam itaque veritatis dolores. Corrupti totam ut eius incidunt reiciendis<br>veritatis asperiores placeat.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"var:preset|spacing|30","padding":{"top":"32px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":364}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:364px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:32px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":53}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:53px;margin-top:0px;margin-bottom:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:outermost/icon-block {"iconName":"wordpress-image","iconColor":"red/red-status-500","iconColorValue":"#E20110","width":"46px","style":{"spacing":{"padding":{"right":"0"}}}} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container has-icon-color has-red/red-status-500-color" style="color:#E20110;width:46px;padding-right:0"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM5 4.5h14c.3 0 .5.2.5.5v8.4l-3-2.9c-.3-.3-.8-.3-1 0L11.9 14 9 12c-.3-.2-.6-.2-.8 0l-3.6 2.6V5c-.1-.3.1-.5.4-.5zm14 15H5c-.3 0-.5-.2-.5-.5v-2.4l4.1-3 3 1.9c.3.2.7.2.9-.1L16 12l3.5 3.4V19c0 .3-.2.5-.5.5z"></path></svg></div></div>
<!-- /wp:outermost/icon-block -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"8px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"28px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":53}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:53px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:28px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":22}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:22px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"351px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"18px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-left text-nowrap has-text-color has-raleway-font-family" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:18px;font-weight:700;line-height:1.2">Ullamco laboris nisi ut aliquip consequat</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":23}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:23px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"520px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"15px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-left text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:15px;font-weight:400;line-height:1.5">Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":53}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:53px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:outermost/icon-block {"iconName":"wordpress-capturePhoto","iconColor":"red/red-status-500","iconColorValue":"#E20110","width":"46px","style":{"spacing":{"padding":{"right":"0"}}}} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container has-icon-color has-red/red-status-500-color" style="color:#E20110;width:46px;padding-right:0"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M12 9.2c-2.2 0-3.9 1.8-3.9 4s1.8 4 3.9 4 4-1.8 4-4-1.8-4-4-4zm0 6.5c-1.4 0-2.4-1.1-2.4-2.5s1.1-2.5 2.4-2.5 2.5 1.1 2.5 2.5-1.1 2.5-2.5 2.5zM20.2 8c-.1 0-.3 0-.5-.1l-2.5-.8c-.4-.1-.8-.4-1.1-.8l-1-1.5c-.4-.5-1-.9-1.7-.9h-2.9c-.6.1-1.2.4-1.6 1l-1 1.5c-.3.3-.6.6-1.1.7l-2.5.8c-.2.1-.4.1-.6.1-1 .2-1.7.9-1.7 1.9v8.3c0 1 .9 1.9 2 1.9h16c1.1 0 2-.8 2-1.9V9.9c0-1-.7-1.7-1.8-1.9zm.3 10.1c0 .2-.2.4-.5.4H4c-.3 0-.5-.2-.5-.4V9.9c0-.1.2-.3.5-.4.2 0 .5-.1.8-.2l2.5-.8c.7-.2 1.4-.6 1.8-1.3l1-1.5c.1-.1.2-.2.4-.2h2.9c.2 0 .3.1.4.2l1 1.5c.4.7 1.1 1.1 1.9 1.4l2.5.8c.3.1.6.1.8.2.3 0 .4.2.4.4v8.1z"></path></svg></div></div>
<!-- /wp:outermost/icon-block -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"8px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"28px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":53}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:53px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:28px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":22}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:22px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"351px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"18px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-left text-nowrap has-text-color has-raleway-font-family" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:18px;font-weight:700;line-height:1.2">Ullamco laboris nisi ut aliquip consequat</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":23}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:23px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"520px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"15px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-left text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:15px;font-weight:400;line-height:1.5">Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":53}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:53px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:outermost/icon-block {"iconName":"wordpress-capturePhoto","iconColor":"red/red-status-500","iconColorValue":"#E20110","width":"46px","style":{"spacing":{"padding":{"right":"0"}}}} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container has-icon-color has-red/red-status-500-color" style="color:#E20110;width:46px;padding-right:0"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M12 9.2c-2.2 0-3.9 1.8-3.9 4s1.8 4 3.9 4 4-1.8 4-4-1.8-4-4-4zm0 6.5c-1.4 0-2.4-1.1-2.4-2.5s1.1-2.5 2.4-2.5 2.5 1.1 2.5 2.5-1.1 2.5-2.5 2.5zM20.2 8c-.1 0-.3 0-.5-.1l-2.5-.8c-.4-.1-.8-.4-1.1-.8l-1-1.5c-.4-.5-1-.9-1.7-.9h-2.9c-.6.1-1.2.4-1.6 1l-1 1.5c-.3.3-.6.6-1.1.7l-2.5.8c-.2.1-.4.1-.6.1-1 .2-1.7.9-1.7 1.9v8.3c0 1 .9 1.9 2 1.9h16c1.1 0 2-.8 2-1.9V9.9c0-1-.7-1.7-1.8-1.9zm.3 10.1c0 .2-.2.4-.5.4H4c-.3 0-.5-.2-.5-.4V9.9c0-.1.2-.3.5-.4.2 0 .5-.1.8-.2l2.5-.8c.7-.2 1.4-.6 1.8-1.3l1-1.5c.1-.1.2-.2.4-.2h2.9c.2 0 .3.1.4.2l1 1.5c.4.7 1.1 1.1 1.9 1.4l2.5.8c.3.1.6.1.8.2.3 0 .4.2.4.4v8.1z"></path></svg></div></div>
<!-- /wp:outermost/icon-block -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"8px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"28px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":53}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:53px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:28px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":22}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:22px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"351px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"18px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-left text-nowrap has-text-color has-raleway-font-family" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:18px;font-weight:700;line-height:1.2">Ullamco laboris nisi ut aliquip consequat</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":23}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:23px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"520px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"15px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-left text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:15px;font-weight:400;line-height:1.5">Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":53}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:53px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:outermost/icon-block {"iconName":"wordpress-capturePhoto","iconColor":"red/red-status-500","iconColorValue":"#E20110","width":"46px","style":{"spacing":{"padding":{"right":"0"}}}} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container has-icon-color has-red/red-status-500-color" style="color:#E20110;width:46px;padding-right:0"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M12 9.2c-2.2 0-3.9 1.8-3.9 4s1.8 4 3.9 4 4-1.8 4-4-1.8-4-4-4zm0 6.5c-1.4 0-2.4-1.1-2.4-2.5s1.1-2.5 2.4-2.5 2.5 1.1 2.5 2.5-1.1 2.5-2.5 2.5zM20.2 8c-.1 0-.3 0-.5-.1l-2.5-.8c-.4-.1-.8-.4-1.1-.8l-1-1.5c-.4-.5-1-.9-1.7-.9h-2.9c-.6.1-1.2.4-1.6 1l-1 1.5c-.3.3-.6.6-1.1.7l-2.5.8c-.2.1-.4.1-.6.1-1 .2-1.7.9-1.7 1.9v8.3c0 1 .9 1.9 2 1.9h16c1.1 0 2-.8 2-1.9V9.9c0-1-.7-1.7-1.8-1.9zm.3 10.1c0 .2-.2.4-.5.4H4c-.3 0-.5-.2-.5-.4V9.9c0-.1.2-.3.5-.4.2 0 .5-.1.8-.2l2.5-.8c.7-.2 1.4-.6 1.8-1.3l1-1.5c.1-.1.2-.2.4-.2h2.9c.2 0 .3.1.4.2l1 1.5c.4.7 1.1 1.1 1.9 1.4l2.5.8c.3.1.6.1.8.2.3 0 .4.2.4.4v8.1z"></path></svg></div></div>
<!-- /wp:outermost/icon-block -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"8px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"28px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":53}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:53px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:28px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":22}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:22px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"351px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"18px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-left text-nowrap has-text-color has-raleway-font-family" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:18px;font-weight:700;line-height:1.2">Ullamco laboris nisi ut aliquip consequat</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":23}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:23px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"520px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"15px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-left text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:15px;font-weight:400;line-height:1.5">Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></section>
<!-- /wp:group -->