<!-- wp:group {"tagName":"section","metadata":{"name":"About Us"},"align":"full","style":{"color":{"background":"rgba(255,88,33,0.03)"},"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|50","bottom":"var:preset|spacing|30","left":"var:preset|spacing|50"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":646}},"className":"full-width","layout":{"type":"constrained","contentSize":"1320px"}} -->
<section class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,88,33,0.03);min-height:646px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--50)"><!-- wp:columns {"verticalAlignment":"center","align":"wide","style":{"border":{"radius":"0px"},"spacing":{"padding":{"top":"55px","right":"0px","bottom":"55px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"blockGap":{"top":"0px","left":"20px"}},"className":"full-width","customStyle":{"style":""},"layout":{"selfStretch":"fit","flexSize":null}}} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:55px;padding-right:0px;padding-bottom:55px;padding-left:0px"><!-- wp:column {"verticalAlignment":"center","width":"40%","style":{"spacing":{"padding":{"top":"0","bottom":"0"},"blockGap":"0px"}},"className":"animate-aos data-aos_fade-up data-aos-delay_200"} -->
<div class="wp-block-column is-vertically-aligned-center animate-aos data-aos_fade-up data-aos-delay_200" style="padding-top:0;padding-bottom:0;flex-basis:40%"><!-- wp:group {"layout":{"type":"constrained","contentSize":"100%"}} -->
<div class="wp-block-group"><!-- wp:image {"scale":"cover","style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"blob-image"} -->
<figure class="wp-block-image blob-image" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><img src="@asset('images/about.jpg')" alt="" style="object-fit:cover"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"","className":"animate-aos data-aos_fade-up data-aos-delay_100"} -->
<div class="wp-block-column is-vertically-aligned-center animate-aos data-aos_fade-up data-aos-delay_100"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":526}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"center","flexWrap":"wrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:526px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":39}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:39px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:heading {"textAlign":"left","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"32px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-left full-width has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:32px;font-weight:700;line-height:1.2">About Us</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"16px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-left full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:16px;font-weight:400;line-height:1.5">Dolor iure expedita id fuga asperiores qui sunt consequatur minima. Quidem voluptas deleniti. Sit quia<br>molestiae quia quas qui magnam itaque veritatis dolores. Corrupti totam ut eius incidunt reiciendis<br>veritatis asperiores placeat.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0","padding":{"top":"30px","right":"0px","bottom":"30px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":364},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"space-between"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:364px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:30px;padding-right:0px;padding-bottom:30px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":53}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"left","verticalAlignment":"top","flexWrap":"nowrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:53px;margin-top:0px;margin-bottom:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:outermost/icon-block {"iconName":"wordpress-image","iconColor":"red/red-status-500","iconColorValue":"#E20110","width":"46px","style":{"spacing":{"padding":{"right":"0"}}}} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container has-icon-color has-red/red-status-500-color" style="color:#E20110;width:46px;padding-right:0"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM5 4.5h14c.3 0 .5.2.5.5v8.4l-3-2.9c-.3-.3-.8-.3-1 0L11.9 14 9 12c-.3-.2-.6-.2-.8 0l-3.6 2.6V5c-.1-.3.1-.5.4-.5zm14 15H5c-.3 0-.5-.2-.5-.5v-2.4l4.1-3 3 1.9c.3.2.7.2.9-.1L16 12l3.5 3.4V19c0 .3-.2.5-.5.5z"></path></svg></div></div>
<!-- /wp:outermost/icon-block -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"8px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"28px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":53}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center","flexWrap":"wrap"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:53px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:28px"><!-- wp:heading {"textAlign":"left","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"700"}},"className":"text-nowrap","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-left text-nowrap has-text-color has-headline-font-family" style="color:rgba(71,61,58,1);font-size:18px;font-style:normal;font-weight:700">Ullamco laboris nisi ut aliquip consequat</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"15px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-left text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:15px;font-weight:400;line-height:1.5">Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":53}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"left","verticalAlignment":"top","flexWrap":"nowrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:53px;margin-top:0px;margin-bottom:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:outermost/icon-block {"iconName":"wordpress-image","iconColor":"red/red-status-500","iconColorValue":"#E20110","width":"46px","style":{"spacing":{"padding":{"right":"0"}}}} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container has-icon-color has-red/red-status-500-color" style="color:#E20110;width:46px;padding-right:0"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM5 4.5h14c.3 0 .5.2.5.5v8.4l-3-2.9c-.3-.3-.8-.3-1 0L11.9 14 9 12c-.3-.2-.6-.2-.8 0l-3.6 2.6V5c-.1-.3.1-.5.4-.5zm14 15H5c-.3 0-.5-.2-.5-.5v-2.4l4.1-3 3 1.9c.3.2.7.2.9-.1L16 12l3.5 3.4V19c0 .3-.2.5-.5.5z"></path></svg></div></div>
<!-- /wp:outermost/icon-block -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"8px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"28px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":53}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center","flexWrap":"wrap"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:53px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:28px"><!-- wp:heading {"textAlign":"left","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"700"}},"className":"text-nowrap","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-left text-nowrap has-text-color has-headline-font-family" style="color:rgba(71,61,58,1);font-size:18px;font-style:normal;font-weight:700">Ullamco laboris nisi ut aliquip consequat</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"15px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-left text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:15px;font-weight:400;line-height:1.5">Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":53}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"left","verticalAlignment":"top","flexWrap":"nowrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:53px;margin-top:0px;margin-bottom:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:outermost/icon-block {"iconName":"wordpress-image","iconColor":"red/red-status-500","iconColorValue":"#E20110","width":"46px","style":{"spacing":{"padding":{"right":"0"}}}} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container has-icon-color has-red/red-status-500-color" style="color:#E20110;width:46px;padding-right:0"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM5 4.5h14c.3 0 .5.2.5.5v8.4l-3-2.9c-.3-.3-.8-.3-1 0L11.9 14 9 12c-.3-.2-.6-.2-.8 0l-3.6 2.6V5c-.1-.3.1-.5.4-.5zm14 15H5c-.3 0-.5-.2-.5-.5v-2.4l4.1-3 3 1.9c.3.2.7.2.9-.1L16 12l3.5 3.4V19c0 .3-.2.5-.5.5z"></path></svg></div></div>
<!-- /wp:outermost/icon-block -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"8px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"28px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":53}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center","flexWrap":"wrap"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:53px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:28px"><!-- wp:heading {"textAlign":"left","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"700"}},"className":"text-nowrap","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-left text-nowrap has-text-color has-headline-font-family" style="color:rgba(71,61,58,1);font-size:18px;font-style:normal;font-weight:700">Ullamco laboris nisi ut aliquip consequat</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"15px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-left text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:15px;font-weight:400;line-height:1.5">Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":53}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"left","verticalAlignment":"top","flexWrap":"nowrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:53px;margin-top:0px;margin-bottom:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:outermost/icon-block {"iconName":"wordpress-image","iconColor":"red/red-status-500","iconColorValue":"#E20110","width":"46px","style":{"spacing":{"padding":{"right":"0"}}}} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container has-icon-color has-red/red-status-500-color" style="color:#E20110;width:46px;padding-right:0"><svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM5 4.5h14c.3 0 .5.2.5.5v8.4l-3-2.9c-.3-.3-.8-.3-1 0L11.9 14 9 12c-.3-.2-.6-.2-.8 0l-3.6 2.6V5c-.1-.3.1-.5.4-.5zm14 15H5c-.3 0-.5-.2-.5-.5v-2.4l4.1-3 3 1.9c.3.2.7.2.9-.1L16 12l3.5 3.4V19c0 .3-.2.5-.5.5z"></path></svg></div></div>
<!-- /wp:outermost/icon-block -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"8px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"28px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":53}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center","flexWrap":"wrap"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:53px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:28px"><!-- wp:heading {"textAlign":"left","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"700"}},"className":"text-nowrap","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-left text-nowrap has-text-color has-headline-font-family" style="color:rgba(71,61,58,1);font-size:18px;font-style:normal;font-weight:700">Ullamco laboris nisi ut aliquip consequat</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"15px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-left text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:15px;font-weight:400;line-height:1.5">Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></section>
<!-- /wp:group -->