<!-- wp:cover {"url":"@asset('images/hero-bg.jpg')","id":48,"dimRatio":50,"overlayColor":"text-color950","isUserOverlayColor":true,"minHeight":100,"minHeightUnit":"vh","tagName":"section","metadata":{"name":"Banner"},"align":"center","className":"wp-block-group alignfull has-background section"} -->
<section class="wp-block-cover aligncenter wp-block-group alignfull has-background section" style="min-height:100vh"><span aria-hidden="true" class="wp-block-cover__background has-text-color-950-background-color has-background-dim"></span><img class="wp-block-cover__image-background wp-image-48" alt="" src="@asset('images/hero-bg.jpg')" data-object-fit="cover"/><div class="wp-block-cover__inner-container"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"var:preset|spacing|30","padding":{"right":"0px","left":"0px","top":"0px","bottom":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":542}},"className":"full-width","layout":{"type":"constrained","contentSize":"80%"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:542px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"className":"animate-aos data-aos_fade-down data-aos-delay_100","layout":{"type":"constrained"}} -->
<div class="wp-block-group animate-aos data-aos_fade-down data-aos-delay_100"><!-- wp:heading {"textAlign":"left","style":{"color":{"text":"rgba(255,255,255,1)"},"typography":{"fontSize":"48px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-left full-width has-raleway-font-family has-text-color" style="color:rgba(255,255,255,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:48px;font-weight:700;line-height:1.2">Welcome to Our Website</h2>
<!-- /wp:heading -->

<!-- wp:heading {"textAlign":"left","style":{"color":{"text":"rgba(255,255,255,0.8)"},"typography":{"fontSize":"24px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width has-roboto-font-family"} -->
<h2 class="wp-block-heading has-text-align-left full-width has-roboto-font-family has-text-color" style="color:rgba(255,255,255,0.8);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:24px;font-weight:400;line-height:1.5">We are team of talented designers making websites with Bootstrap</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":"56px","width":"0px","style":{"layout":[]}} -->
<div style="height:56px;width:0px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","flexWrap":"wrap","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Why Box"},"align":"full","style":{"color":{"background":"rgba(255,88,33,1)"},"border":{"radius":"4px"},"spacing":{"blockGap":"30px","padding":{"top":"30px","right":"30px","bottom":"30px","left":"30px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":384},"layout":{"selfStretch":"fit","flexSize":null}},"className":"why-box animate-aos data-aos_zoom-out data-aos-delay_200","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull why-box animate-aos data-aos_zoom-out data-aos-delay_200 has-background" style="border-radius:4px;background-color:rgba(255,88,33,1);min-height:384px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px"><!-- wp:heading {"textAlign":"left","style":{"color":{"text":"rgba(255,255,255,1)"},"typography":{"fontSize":"34px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-left has-raleway-font-family has-text-color" style="color:rgba(255,255,255,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:34px;font-weight:700;line-height:1.2">Why Choose Our<br>Services?</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left","style":{"color":{"text":"rgba(255,255,255,1)"},"typography":{"fontSize":"16px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"","fontFamily":"Roboto"} -->
<p class="has-text-align-left has-text-color has-roboto-font-family" style="color:rgba(255,255,255,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:16px;font-weight:400;line-height:1.5">Lorem ipsum dolor sit amet, consectetur<br>adipiscing elit, sed do eiusmod tempor incididunt<br>ut labore et dolore magna aliqua. Duis aute irure<br>dolor in reprehenderit Asperiores dolores sed et.<br>Tenetur quia eos. Autem tempore quibusdam vel<br>necessitatibus optio ad corporis.</p>
<!-- /wp:paragraph -->

<!-- wp:sage/link {"text":"Learn More","borderRadius":{"top":"20px","left":"20px","right":"20px","bottom":"20px"},"className":"more-btn"} -->
<!-- wp:group {"align":"wide","layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"}} -->
<div class="wp-block-group alignwide"><!-- wp:group {"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"typography":{"fontStyle":"normal","fontWeight":"700"},"elements":{"link":{"color":{"text":"var:preset|color|background500"}}},"layout":{"selfStretch":"fit","flexSize":null}},"textColor":"background500","fontFamily":"paragraph"} -->
<p class="has-background-500-color has-text-color has-link-color has-paragraph-font-family" style="font-style:normal;font-weight:700">Learn More</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:sage/icon {"icon":{"name":"chevron-right","iconSet":"sage/bootstrap-icons","source":"\u003csvg fill=\u0022currentColor\u0022 viewBox=\u00220 0 16 16\u0022 height=\u002216\u0022 width=\u002216\u0022 xmlns=\u0022http://www.w3.org/2000/svg\u0022 preserveAspectRatio=\u0022xMidYMid meet\u0022 style=\u0022width:100%;height:100%;\u0022\u003e\u003cpath fillrule=\u0022evenodd\u0022 d=\u0022M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"},"color":"#f2f2f2","size":"24px"} /--></div>
<!-- /wp:group -->
<!-- /wp:sage/link --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":326},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","flexWrap":"wrap","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:326px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"24px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":326}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:326px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:24px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"metadata":{"name":"Icon Box"},"align":"full","style":{"color":{"background":"rgba(255,255,255,0.8)"},"border":{"radius":"10px"},"spacing":{"blockGap":"20px","padding":{"top":"8px","right":"30px","bottom":"8px","left":"30px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":302}},"className":"full-width icon-box animate-aos data-aos_zoom-out","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width icon-box animate-aos data-aos_zoom-out has-background" style="border-radius:10px;background-color:rgba(255,255,255,0.8);min-height:302px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:8px;padding-right:30px;padding-bottom:8px;padding-left:30px"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:sage/icon {"icon":{"name":"file-bar-graph","iconSet":"sage/bootstrap-icons","source":"\u003csvg fill=\u0022currentColor\u0022 viewBox=\u00220 0 16 16\u0022 height=\u002216\u0022 width=\u002216\u0022 xmlns=\u0022http://www.w3.org/2000/svg\u0022 preserveAspectRatio=\u0022xMidYMid meet\u0022 style=\u0022width:100%;height:100%;\u0022\u003e\u003cpath d=\u0022M4.5 12a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5zm3 0a.5.5 0 0 1-.5-.5v-4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5zm3 0a.5.5 0 0 1-.5-.5v-6a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-.5.5z\u0022\u003e\u003c/path\u003e \u003cpath d=\u0022M4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zm0 1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"},"size":"50px"} /--></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"10.8px","bottom":"0px","left":"10.8px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":48}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:48px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:10.8px;padding-bottom:0px;padding-left:10.8px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"188px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:heading {"textAlign":"center","align":"full","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"20px","fontStyle":"normal","fontWeight":"700"}},"fontFamily":"headline"} -->
<h2 class="wp-block-heading alignfull has-text-align-center has-text-color has-headline-font-family" style="color:rgba(71,61,58,1);font-size:20px;font-style:normal;font-weight:700">Corporis voluptates<br>officia eiusmod</h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"8.4px","bottom":"0px","left":"8.4px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":68}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:68px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:8.4px;padding-bottom:0px;padding-left:8.4px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"193px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.7)"},"typography":{"fontSize":"15px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"","fontFamily":"Roboto"} -->
<p class="has-text-align-center has-text-color has-roboto-font-family" style="color:rgba(49,48,48,0.7);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:15px;font-weight:400;line-height:1.5">Consequuntur sunt aut quasi<br>enim aliquam quae harum<br>pariatur laboris nisi ut aliquip</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"24px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":326}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:326px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:24px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"metadata":{"name":"Icon Box"},"align":"full","style":{"color":{"background":"rgba(255,255,255,0.8)"},"border":{"radius":"10px"},"spacing":{"blockGap":"20px","padding":{"top":"8px","right":"30px","bottom":"8px","left":"30px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":302}},"className":"full-width icon-box animate-aos data-aos_zoom-out","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width icon-box animate-aos data-aos_zoom-out has-background" style="border-radius:10px;background-color:rgba(255,255,255,0.8);min-height:302px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:8px;padding-right:30px;padding-bottom:8px;padding-left:30px"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:sage/icon {"icon":{"name":"gem","iconSet":"sage/bootstrap-icons","source":"\u003csvg fill=\u0022currentColor\u0022 viewBox=\u00220 0 16 16\u0022 height=\u002216\u0022 width=\u002216\u0022 xmlns=\u0022http://www.w3.org/2000/svg\u0022 preserveAspectRatio=\u0022xMidYMid meet\u0022 style=\u0022width:100%;height:100%;\u0022\u003e\u003cpath d=\u0022M3.1.7a.5.5 0 0 1 .4-.2h9a.5.5 0 0 1 .4.2l2.976 3.974c.149.185.156.45.01.644L8.4 15.3a.5.5 0 0 1-.8 0L.1 5.3a.5.5 0 0 1 0-.6zm11.386 3.785-1.806-2.41-.776 2.413zm-3.633.004.961-2.989H4.186l.963 2.995zM5.47 5.495 8 13.366l2.532-7.876zm-1.371-.999-.78-2.422-1.818 2.425zM1.499 5.5l5.113 6.817-2.192-6.82zm7.889 6.817 5.123-6.83-2.928.002z\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"},"size":"50px","hover":"nohover"} /--></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"29.1px","bottom":"0px","left":"29.1px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":48}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:48px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:29.1px;padding-bottom:0px;padding-left:29.1px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"152px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:heading {"textAlign":"center","align":"full","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"20px","fontStyle":"normal","fontWeight":"700"}},"fontFamily":"headline"} -->
<h2 class="wp-block-heading alignfull has-text-align-center has-text-color has-headline-font-family" style="color:rgba(71,61,58,1);font-size:20px;font-style:normal;font-weight:700">Ullamco laboris<br>ladore pan</h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"3.7px","bottom":"0px","left":"3.7px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":68}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:68px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:3.7px;padding-bottom:0px;padding-left:3.7px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"203px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.7)"},"typography":{"fontSize":"15px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"","fontFamily":"Roboto"} -->
<p class="has-text-align-center has-text-color has-roboto-font-family" style="color:rgba(49,48,48,0.7);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:15px;font-weight:400;line-height:1.5">Excepteur sint occaecat<br>cupidatat non proident, sunt in<br>culpa qui officia deserunt</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"24px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":326}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:326px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:24px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"metadata":{"name":"Icon Box"},"align":"full","style":{"color":{"background":"rgba(255,255,255,0.8)"},"border":{"radius":"10px"},"spacing":{"blockGap":"20px","padding":{"top":"8px","right":"30px","bottom":"8px","left":"30px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":302}},"className":"full-width icon-box animate-aos data-aos_zoom-out","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width icon-box animate-aos data-aos_zoom-out has-background" style="border-radius:10px;background-color:rgba(255,255,255,0.8);min-height:302px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:8px;padding-right:30px;padding-bottom:8px;padding-left:30px"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:sage/icon {"icon":{"name":"inboxes","iconSet":"sage/bootstrap-icons","source":"\u003csvg fill=\u0022currentColor\u0022 viewBox=\u00220 0 16 16\u0022 height=\u002216\u0022 width=\u002216\u0022 xmlns=\u0022http://www.w3.org/2000/svg\u0022 preserveAspectRatio=\u0022xMidYMid meet\u0022 style=\u0022width:100%;height:100%;\u0022\u003e\u003cpath d=\u0022M4.98 1a.5.5 0 0 0-.39.188L1.54 5H6a.5.5 0 0 1 .5.5 1.5 1.5 0 0 0 3 0A.5.5 0 0 1 10 5h4.46l-3.05-3.812A.5.5 0 0 0 11.02 1zm9.954 5H10.45a2.5 2.5 0 0 1-4.9 0H1.066l.32 2.562A.5.5 0 0 0 1.884 9h12.234a.5.5 0 0 0 .496-.438zM3.809.563A1.5 1.5 0 0 1 4.981 0h6.038a1.5 1.5 0 0 1 1.172.563l3.7 4.625a.5.5 0 0 1 .105.374l-.39 3.124A1.5 1.5 0 0 1 14.117 10H1.883A1.5 1.5 0 0 1 .394 8.686l-.39-3.124a.5.5 0 0 1 .106-.374zM.125 11.17A.5.5 0 0 1 .5 11H6a.5.5 0 0 1 .5.5 1.5 1.5 0 0 0 3 0 .5.5 0 0 1 .5-.5h5.5a.5.5 0 0 1 .496.562l-.39 3.124A1.5 1.5 0 0 1 14.117 16H1.883a1.5 1.5 0 0 1-1.489-1.314l-.39-3.124a.5.5 0 0 1 .121-.393zm.941.83.32 2.562a.5.5 0 0 0 .497.438h12.234a.5.5 0 0 0 .496-.438l.32-2.562H10.45a2.5 2.5 0 0 1-4.9 0z\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"},"size":"50px"} /--></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"7.8px","bottom":"0px","left":"7.8px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":48}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:48px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:7.8px;padding-bottom:0px;padding-left:7.8px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"194px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:heading {"textAlign":"center","align":"full","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"20px","fontStyle":"normal","fontWeight":"700"}},"fontFamily":"headline"} -->
<h2 class="wp-block-heading alignfull has-text-align-center has-text-color has-headline-font-family" style="color:rgba(71,61,58,1);font-size:20px;font-style:normal;font-weight:700">Labore consequatur<br>incidid dolore</h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"1.3px","bottom":"0px","left":"1.3px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":68}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:68px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:1.3px;padding-bottom:0px;padding-left:1.3px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"208px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.7)"},"typography":{"fontSize":"15px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"","fontFamily":"Roboto"} -->
<p class="has-text-align-center has-text-color has-roboto-font-family" style="color:rgba(49,48,48,0.7);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:15px;font-weight:400;line-height:1.5">Aut suscipit aut cum nemo<br>deleniti aut omnis. Doloribus ut<br>maiores omnis facere</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div></section>
<!-- /wp:cover -->