<!-- wp:group {"tagName":"section","metadata":{"name":"Pricing"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"var:preset|spacing|30","right":"0px","bottom":"var:preset|spacing|30","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":693}},"className":"full-width pricing","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"space-between","flexWrap":"nowrap"}} -->
<section class="wp-block-group alignfull full-width pricing has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:693px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:var(--wp--preset--spacing--30);padding-right:0px;padding-bottom:var(--wp--preset--spacing--30);padding-left:0px"><!-- wp:group {"align":"full","layout":{"type":"constrained","contentSize":"1320px"}} -->
<div class="wp-block-group alignfull"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"14px","padding":{"top":"0px","right":"12px","bottom":"var:preset|spacing|30","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":138}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center","flexWrap":"nowrap"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:138px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:var(--wp--preset--spacing--30);padding-left:12px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":39}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top","flexWrap":"nowrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:39px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"1296px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"32px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:32px;font-weight:700;line-height:1.2">Pricing</h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":24}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top","flexWrap":"nowrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:24px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"1296px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"16px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:16px;font-weight:400;line-height:1.5">Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:columns {"verticalAlignment":null,"align":"wide","style":{"border":{"radius":"0px"},"spacing":{"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"blockGap":{"top":"0px","left":"0px"}},"className":"full-width","customStyle":{"style":""}}} -->
<div class="wp-block-columns alignwide" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:column {"verticalAlignment":"top","width":"25%","layout":{"type":"default"}} -->
<div class="wp-block-column is-vertically-aligned-top" style="flex-basis:25%"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"16px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":451}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:451px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:16px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":435}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:435px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"align":"full","style":{"border":{"radius":"5px"},"spacing":{"blockGap":"20px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":435}},"className":"full-width pricing-item","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width pricing-item" style="border-radius:5px;min-height:435px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"padding":{"top":"15px","bottom":"15px"}},"color":{"background":"#3130300d"}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#3130300d;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:15px;padding-bottom:15px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(49,48,48,0.8)"},"typography":{"fontSize":"16px","fontStyle":"normal","fontWeight":"700"}},"className":"full-width text-nowrap","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-text-color has-headline-font-family" style="color:rgba(49,48,48,0.8);font-size:16px;font-style:normal;font-weight:700">Free</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|50","bottom":"0.3px","left":"var:preset|spacing|50"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":43}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:43px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--50);padding-bottom:0.3px;padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"20px","fontWeight":"600","lineHeight":"2.1"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-center text-nowrap has-text-color has-raleway-font-family" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:20px;font-weight:600;line-height:2.1">$</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"2.6553144454956055px"}}},"layout":{"contentSize":"22.441936492919922px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:2.6553144454956055px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"36px","fontWeight":"600","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:36px;font-weight:600;line-height:1.2">0</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"","type":"constrained","wideSize":""}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.6)"},"typography":{"fontSize":"16px","fontWeight":"300","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-center text-nowrap has-text-color has-raleway-font-family" style="color:rgba(49,48,48,0.6);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:16px;font-weight:300;line-height:1.2"> / month</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"3px","right":"0px","bottom":"15px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":198}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:198px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:3px;padding-right:0px;padding-bottom:15px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|50","bottom":"16px","left":"var:preset|spacing|50"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--50);padding-bottom:16px;padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"98.83999633789062px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Aida dere</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"136.6699981689453px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Nec feugiat nisl</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"171.97999572753906px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Nulla at volutpat dola</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"138.24000549316406px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.6)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,0.6);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Pharetra massa</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"153.67999267578125px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.6)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,0.6);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Massa ultricies mi</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"color":{"background":"rgba(49,48,48,0.05)"},"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"16px","right":"0px","bottom":"20px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":75}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(49,48,48,0.05);min-height:75px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:16px;padding-right:0px;padding-bottom:20px;padding-left:0px"><!-- wp:group {"align":"full","layout":{"type":"constrained","contentSize":"129px"}} -->
<div class="wp-block-group alignfull"><!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"main-color500","textColor":"background500","width":100,"style":{"spacing":{"padding":{"left":"10px","right":"10px","top":"8px","bottom":"8px"}},"typography":{"fontStyle":"normal","fontWeight":"700"},"elements":{"link":{"color":{"text":"var:preset|color|background500"}}},"border":{"radius":"5px"}},"className":"is-style-default","fontSize":"small","fontFamily":"paragraph"} -->
<div class="wp-block-button has-custom-width wp-block-button__width-100 has-custom-font-size is-style-default has-paragraph-font-family has-small-font-size" style="font-style:normal;font-weight:700"><a class="wp-block-button__link has-background-500-color has-main-color-500-background-color has-text-color has-background has-link-color wp-element-button" style="border-radius:5px;padding-top:8px;padding-right:10px;padding-bottom:8px;padding-left:10px">Buy Now</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"top","width":"25%"} -->
<div class="wp-block-column is-vertically-aligned-top" style="flex-basis:25%"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"16px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":451}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:451px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:16px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":435}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:435px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"align":"full","style":{"border":{"radius":"5px"},"spacing":{"blockGap":"20px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":435}},"className":"full-width featured pricing-item","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width featured pricing-item" style="border-radius:5px;min-height:435px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","bottom":"0px"},"padding":{"top":"15px","bottom":"15px"}},"layout":{"selfStretch":"fit","flexSize":null}},"backgroundColor":"main-color500","layout":{"type":"constrained","wideSize":"","contentSize":""}} -->
<div class="wp-block-group has-main-color-500-background-color has-background" style="margin-top:0px;margin-bottom:0px;padding-top:15px;padding-bottom:15px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(255,255,255,1)"},"typography":{"fontSize":"16px","fontStyle":"normal","fontWeight":"700"}},"className":"full-width"} -->
<h2 class="wp-block-heading has-text-align-center full-width has-text-color" style="color:rgba(255,255,255,1);font-size:16px;font-style:normal;font-weight:700">Business</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"0.3px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":43}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:43px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:0.3px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"20px","fontWeight":"600","lineHeight":"2.1"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-center text-nowrap has-text-color has-raleway-font-family" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:20px;font-weight:600;line-height:2.1">$</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"2.6653242111206055px"}}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:2.6653242111206055px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"36px","fontWeight":"600","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:36px;font-weight:600;line-height:1.2">19</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.6)"},"typography":{"fontSize":"16px","fontWeight":"300","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-center text-nowrap has-text-color has-raleway-font-family" style="color:rgba(49,48,48,0.6);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:16px;font-weight:300;line-height:1.2"> / month</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"3px","right":"0px","bottom":"15px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":198}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:198px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:3px;padding-right:0px;padding-bottom:15px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|50","bottom":"16px","left":"var:preset|spacing|50"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--50);padding-bottom:16px;padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"98.83999633789062px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Aida dere</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"136.6699981689453px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Nec feugiat nisl</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"171.97999572753906px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Nulla at volutpat dola</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"138.24000549316406px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Pharetra massa</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"153.67999267578125px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.6)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,0.6);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Massa ultricies mi</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"color":{"background":"rgba(49,48,48,0.05)"},"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"16px","right":"0px","bottom":"20px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":75}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(49,48,48,0.05);min-height:75px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:16px;padding-right:0px;padding-bottom:20px;padding-left:0px"><!-- wp:group {"align":"full","layout":{"type":"constrained","contentSize":"129px"}} -->
<div class="wp-block-group alignfull"><!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"main-color500","textColor":"background500","width":100,"style":{"spacing":{"padding":{"left":"10px","right":"10px","top":"8px","bottom":"8px"}},"typography":{"fontStyle":"normal","fontWeight":"700"},"elements":{"link":{"color":{"text":"var:preset|color|background500"}}},"border":{"radius":"5px"}},"className":"is-style-default","fontSize":"small","fontFamily":"paragraph"} -->
<div class="wp-block-button has-custom-width wp-block-button__width-100 has-custom-font-size is-style-default has-paragraph-font-family has-small-font-size" style="font-style:normal;font-weight:700"><a class="wp-block-button__link has-background-500-color has-main-color-500-background-color has-text-color has-background has-link-color wp-element-button" style="border-radius:5px;padding-top:8px;padding-right:10px;padding-bottom:8px;padding-left:10px" rel="">Buy Now</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"top","width":"25%"} -->
<div class="wp-block-column is-vertically-aligned-top" style="flex-basis:25%"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"16px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":451}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:451px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:16px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":435}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:435px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"align":"full","style":{"border":{"radius":"5px"},"spacing":{"blockGap":"20px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":435}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:5px;min-height:435px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"padding":{"top":"15px","bottom":"15px"}},"color":{"background":"#3130300d"}},"layout":{"contentSize":"78.68999481201172px","type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#3130300d;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:15px;padding-bottom:15px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(49,48,48,0.8)"},"typography":{"fontSize":"16px","fontStyle":"normal","fontWeight":"700"}},"className":"full-width text-nowrap","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-text-color has-headline-font-family" style="color:rgba(49,48,48,0.8);font-size:16px;font-style:normal;font-weight:700">Developer</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"0.3px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":43}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:43px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:0.3px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"20px","fontWeight":"600","lineHeight":"2.1"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-center text-nowrap has-text-color has-raleway-font-family" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:20px;font-weight:600;line-height:2.1">$</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"2.6555585861206055px"}}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:2.6555585861206055px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"36px","fontWeight":"600","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:36px;font-weight:600;line-height:1.2">29</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.6)"},"typography":{"fontSize":"16px","fontWeight":"300","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-center text-nowrap has-text-color has-raleway-font-family" style="color:rgba(49,48,48,0.6);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:16px;font-weight:300;line-height:1.2"> / month</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"3px","right":"0px","bottom":"15px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":198}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:198px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:3px;padding-right:0px;padding-bottom:15px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|50","bottom":"16px","left":"var:preset|spacing|50"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--50);padding-bottom:16px;padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"98.83999633789062px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Aida dere</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"136.6699981689453px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Nec feugiat nisl</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"171.97999572753906px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Nulla at volutpat dola</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"138.24000549316406px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Pharetra massa</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"153.67999267578125px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Massa ultricies mi</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"color":{"background":"rgba(49,48,48,0.05)"},"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"16px","right":"0px","bottom":"20px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":75}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(49,48,48,0.05);min-height:75px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:16px;padding-right:0px;padding-bottom:20px;padding-left:0px"><!-- wp:group {"align":"full","layout":{"type":"constrained","contentSize":"129px"}} -->
<div class="wp-block-group alignfull"><!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"main-color500","textColor":"background500","width":100,"style":{"spacing":{"padding":{"left":"10px","right":"10px","top":"8px","bottom":"8px"}},"typography":{"fontStyle":"normal","fontWeight":"700"},"elements":{"link":{"color":{"text":"var:preset|color|background500"}}},"border":{"radius":"5px"}},"className":"is-style-default","fontSize":"small","fontFamily":"paragraph"} -->
<div class="wp-block-button has-custom-width wp-block-button__width-100 has-custom-font-size is-style-default has-paragraph-font-family has-small-font-size" style="font-style:normal;font-weight:700"><a class="wp-block-button__link has-background-500-color has-main-color-500-background-color has-text-color has-background has-link-color wp-element-button" style="border-radius:5px;padding-top:8px;padding-right:10px;padding-bottom:8px;padding-left:10px">Buy Now</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"top","width":"25%"} -->
<div class="wp-block-column is-vertically-aligned-top" style="flex-basis:25%"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"16px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":451}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:451px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:16px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":435}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:435px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"align":"full","style":{"border":{"radius":"5px"},"spacing":{"blockGap":"20px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":435}},"className":"full-width pricing-item","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width pricing-item" style="border-radius:5px;min-height:435px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"16px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"20px","padding":{"top":"var:preset|spacing|30","right":"var:preset|spacing|30","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"padding":{"top":"15px","bottom":"15px"}},"color":{"background":"#3130300d"}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group has-background" style="background-color:#3130300d;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:15px;padding-bottom:15px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(49,48,48,0.8)"},"typography":{"fontSize":"16px","fontStyle":"normal","fontWeight":"700"}},"className":"full-width text-nowrap","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-text-color has-headline-font-family" style="color:rgba(49,48,48,0.8);font-size:16px;font-style:normal;font-weight:700">Ultimate</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"0.3px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":43}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:43px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:0.3px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"20px","fontWeight":"600","lineHeight":"2.1"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-center text-nowrap has-text-color has-raleway-font-family" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:20px;font-weight:600;line-height:2.1">$</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"2.6655683517456055px"}}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:2.6655683517456055px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"36px","fontWeight":"600","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:36px;font-weight:600;line-height:1.2">49</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.6)"},"typography":{"fontSize":"16px","fontWeight":"300","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"text-nowrap","fontFamily":"Raleway"} -->
<p class="has-text-align-center text-nowrap has-text-color has-raleway-font-family" style="color:rgba(49,48,48,0.6);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:16px;font-weight:300;line-height:1.2"> / month</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"3px","right":"0px","bottom":"15px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":198}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:198px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:3px;padding-right:0px;padding-bottom:15px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|50","bottom":"16px","left":"var:preset|spacing|50"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--50);padding-bottom:16px;padding-left:var(--wp--preset--spacing--50)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"98.83999633789062px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Aida dere</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"136.6699981689453px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Nec feugiat nisl</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"171.97999572753906px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Nulla at volutpat dola</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"138.24000549316406px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Pharetra massa</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"var:preset|spacing|40","bottom":"16px","left":"var:preset|spacing|40"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":36}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:36px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--40);padding-bottom:16px;padding-left:var(--wp--preset--spacing--40)"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"153.67999267578125px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.4"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width text-nowrap","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width text-nowrap has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.4">Massa ultricies mi</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"color":{"background":"rgba(49,48,48,0.05)"},"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"16px","right":"0px","bottom":"20px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":75}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(49,48,48,0.05);min-height:75px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:16px;padding-right:0px;padding-bottom:20px;padding-left:0px"><!-- wp:group {"align":"full","layout":{"type":"constrained","contentSize":"129px"}} -->
<div class="wp-block-group alignfull"><!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"main-color500","textColor":"background500","width":100,"style":{"spacing":{"padding":{"left":"10px","right":"10px","top":"8px","bottom":"8px"}},"typography":{"fontStyle":"normal","fontWeight":"700"},"elements":{"link":{"color":{"text":"var:preset|color|background500"}}},"border":{"radius":"5px"}},"className":"is-style-default","fontSize":"small","fontFamily":"paragraph"} -->
<div class="wp-block-button has-custom-width wp-block-button__width-100 has-custom-font-size is-style-default has-paragraph-font-family has-small-font-size" style="font-style:normal;font-weight:700"><a class="wp-block-button__link has-background-500-color has-main-color-500-background-color has-text-color has-background has-link-color wp-element-button" style="border-radius:5px;padding-top:8px;padding-right:10px;padding-bottom:8px;padding-left:10px">Buy Now</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->