<!-- wp:group {"tagName":"section","metadata":{"name":"Services"},"align":"full","style":{"color":{"background":"rgba(255,88,33,0.03)"},"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"var:preset|spacing|40","right":"0px","bottom":"var:preset|spacing|40","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":829}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<section class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,88,33,0.03);min-height:829px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:var(--wp--preset--spacing--40);padding-right:0px;padding-bottom:var(--wp--preset--spacing--40);padding-left:0px"><!-- wp:group {"metadata":{"name":"Services Content"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"0px","right":"12px","bottom":"var:preset|spacing|30","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":162}},"className":"animate-aos data-aos_fade-up","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up" style="border-radius:0px;min-height:162px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:var(--wp--preset--spacing--30);padding-left:12px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"0px","right":"var:preset|spacing|50","bottom":"0px","left":"var:preset|spacing|50"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":39}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:39px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--50);padding-bottom:0px;padding-left:var(--wp--preset--spacing--50)"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"32px","fontWeight":"700","lineHeight":"1.2","fontStyle":"normal"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color has-headline-font-family" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:32px;font-style:normal;font-weight:700;line-height:1.2">Services</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"16px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:16px;font-weight:400;line-height:1.5">Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:columns {"verticalAlignment":"center","metadata":{"name":"Services List"},"align":"wide","style":{"border":{"radius":"0px"},"spacing":{"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"blockGap":{"top":"16px","left":"16px"}},"className":"full-width","customStyle":{"style":{"width":"100%","max-width":"1320px"}}}} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"space-between"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"animate-aos data-aos_fade-up data-aos-delay_100","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_100" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:outermost/icon-block {"iconName":"wordpress-shipping","width":"70px"} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container" style="width:70px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6.75C3 5.784 3.784 5 4.75 5H15V7.313l.05.027 5.056 2.73.394.212v3.468a1.75 1.75 0 01-1.75 1.75h-.012a2.5 2.5 0 11-4.975 0H9.737a2.5 2.5 0 11-4.975 0H3V6.75zM13.5 14V6.5H4.75a.25.25 0 00-.25.25V14h.965a2.493 2.493 0 011.785-.75c.7 0 1.332.287 1.785.75H13.5zm4.535 0h.715a.25.25 0 00.25-.25v-2.573l-4-2.16v4.568a2.487 2.487 0 011.25-.335c.7 0 1.332.287 1.785.75zM6.282 15.5a1.002 1.002 0 00.968 1.25 1 1 0 10-.968-1.25zm9 0a1 1 0 101.937.498 1 1 0 00-1.938-.498z"></path></svg></div></div>
<!-- /wp:outermost/icon-block --></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"animate-aos data-aos_fade-up data-aos-delay_200","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_200" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:outermost/icon-block {"iconName":"wordpress-shipping","width":"70px"} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container" style="width:70px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6.75C3 5.784 3.784 5 4.75 5H15V7.313l.05.027 5.056 2.73.394.212v3.468a1.75 1.75 0 01-1.75 1.75h-.012a2.5 2.5 0 11-4.975 0H9.737a2.5 2.5 0 11-4.975 0H3V6.75zM13.5 14V6.5H4.75a.25.25 0 00-.25.25V14h.965a2.493 2.493 0 011.785-.75c.7 0 1.332.287 1.785.75H13.5zm4.535 0h.715a.25.25 0 00.25-.25v-2.573l-4-2.16v4.568a2.487 2.487 0 011.25-.335c.7 0 1.332.287 1.785.75zM6.282 15.5a1.002 1.002 0 00.968 1.25 1 1 0 10-.968-1.25zm9 0a1 1 0 101.937.498 1 1 0 00-1.938-.498z"></path></svg></div></div>
<!-- /wp:outermost/icon-block --></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"space-between"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"animate-aos data-aos_fade-up data-aos-delay_300","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_300" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:outermost/icon-block {"iconName":"wordpress-shipping","width":"70px"} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container" style="width:70px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6.75C3 5.784 3.784 5 4.75 5H15V7.313l.05.027 5.056 2.73.394.212v3.468a1.75 1.75 0 01-1.75 1.75h-.012a2.5 2.5 0 11-4.975 0H9.737a2.5 2.5 0 11-4.975 0H3V6.75zM13.5 14V6.5H4.75a.25.25 0 00-.25.25V14h.965a2.493 2.493 0 011.785-.75c.7 0 1.332.287 1.785.75H13.5zm4.535 0h.715a.25.25 0 00.25-.25v-2.573l-4-2.16v4.568a2.487 2.487 0 011.25-.335c.7 0 1.332.287 1.785.75zM6.282 15.5a1.002 1.002 0 00.968 1.25 1 1 0 10-.968-1.25zm9 0a1 1 0 101.937.498 1 1 0 00-1.938-.498z"></path></svg></div></div>
<!-- /wp:outermost/icon-block --></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"animate-aos data-aos_fade-up data-aos-delay_400","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_400" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:outermost/icon-block {"iconName":"wordpress-shipping","width":"70px"} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container" style="width:70px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6.75C3 5.784 3.784 5 4.75 5H15V7.313l.05.027 5.056 2.73.394.212v3.468a1.75 1.75 0 01-1.75 1.75h-.012a2.5 2.5 0 11-4.975 0H9.737a2.5 2.5 0 11-4.975 0H3V6.75zM13.5 14V6.5H4.75a.25.25 0 00-.25.25V14h.965a2.493 2.493 0 011.785-.75c.7 0 1.332.287 1.785.75H13.5zm4.535 0h.715a.25.25 0 00.25-.25v-2.573l-4-2.16v4.568a2.487 2.487 0 011.25-.335c.7 0 1.332.287 1.785.75zM6.282 15.5a1.002 1.002 0 00.968 1.25 1 1 0 10-.968-1.25zm9 0a1 1 0 101.937.498 1 1 0 00-1.938-.498z"></path></svg></div></div>
<!-- /wp:outermost/icon-block --></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"space-between"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"animate-aos data-aos_fade-up data-aos-delay_500","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_500" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:outermost/icon-block {"iconName":"wordpress-shipping","width":"70px"} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container" style="width:70px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6.75C3 5.784 3.784 5 4.75 5H15V7.313l.05.027 5.056 2.73.394.212v3.468a1.75 1.75 0 01-1.75 1.75h-.012a2.5 2.5 0 11-4.975 0H9.737a2.5 2.5 0 11-4.975 0H3V6.75zM13.5 14V6.5H4.75a.25.25 0 00-.25.25V14h.965a2.493 2.493 0 011.785-.75c.7 0 1.332.287 1.785.75H13.5zm4.535 0h.715a.25.25 0 00.25-.25v-2.573l-4-2.16v4.568a2.487 2.487 0 011.25-.335c.7 0 1.332.287 1.785.75zM6.282 15.5a1.002 1.002 0 00.968 1.25 1 1 0 10-.968-1.25zm9 0a1 1 0 101.937.498 1 1 0 00-1.938-.498z"></path></svg></div></div>
<!-- /wp:outermost/icon-block --></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"animate-aos data-aos_fade-up data-aos-delay_600","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_600" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:outermost/icon-block {"iconName":"wordpress-shipping","width":"70px"} -->
<div class="wp-block-outermost-icon-block"><div class="icon-container" style="width:70px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6.75C3 5.784 3.784 5 4.75 5H15V7.313l.05.027 5.056 2.73.394.212v3.468a1.75 1.75 0 01-1.75 1.75h-.012a2.5 2.5 0 11-4.975 0H9.737a2.5 2.5 0 11-4.975 0H3V6.75zM13.5 14V6.5H4.75a.25.25 0 00-.25.25V14h.965a2.493 2.493 0 011.785-.75c.7 0 1.332.287 1.785.75H13.5zm4.535 0h.715a.25.25 0 00.25-.25v-2.573l-4-2.16v4.568a2.487 2.487 0 011.25-.335c.7 0 1.332.287 1.785.75zM6.282 15.5a1.002 1.002 0 00.968 1.25 1 1 0 10-.968-1.25zm9 0a1 1 0 101.937.498 1 1 0 00-1.938-.498z"></path></svg></div></div>
<!-- /wp:outermost/icon-block --></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></section>
<!-- /wp:group -->