<!-- wp:group {"tagName":"section","metadata":{"name":"Services"},"align":"full","style":{"color":{"background":"rgba(255,88,33,0.03)"},"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"var:preset|spacing|40","right":"0px","bottom":"var:preset|spacing|40","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":829}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<section class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,88,33,0.03);min-height:829px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:var(--wp--preset--spacing--40);padding-right:0px;padding-bottom:var(--wp--preset--spacing--40);padding-left:0px"><!-- wp:group {"metadata":{"name":"Services Content"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"0px","right":"12px","bottom":"var:preset|spacing|30","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":162}},"className":"animate-aos data-aos_fade-up","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up" style="border-radius:0px;min-height:162px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:var(--wp--preset--spacing--30);padding-left:12px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"0px","right":"var:preset|spacing|50","bottom":"0px","left":"var:preset|spacing|50"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":39}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:39px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:var(--wp--preset--spacing--50);padding-bottom:0px;padding-left:var(--wp--preset--spacing--50)"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"32px","fontWeight":"700","lineHeight":"1.2","fontStyle":"normal"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color has-headline-font-family" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:32px;font-style:normal;font-weight:700;line-height:1.2">Services</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"16px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:16px;font-weight:400;line-height:1.5">Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:columns {"verticalAlignment":"center","metadata":{"name":"Services List"},"align":"wide","style":{"border":{"radius":"0px"},"spacing":{"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"blockGap":{"top":"16px","left":"16px"}},"className":"full-width","customStyle":{"style":{"width":"100%","max-width":"1320px"}}}} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"space-between"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"animate-aos data-aos_fade-up data-aos-delay_100","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_100" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:sage/icon {"icon":{"name":"activity","iconSet":"sage/bootstrap-icons","source":"\u003csvg fill=\u0022currentColor\u0022 viewBox=\u00220 0 16 16\u0022 height=\u002216\u0022 width=\u002216\u0022 xmlns=\u0022http://www.w3.org/2000/svg\u0022 preserveAspectRatio=\u0022xMidYMid meet\u0022 style=\u0022width:100%;height:100%;\u0022\u003e\u003cpath fillrule=\u0022evenodd\u0022 d=\u0022M6 2a.5.5 0 0 1 .47.33L10 12.036l1.53-4.208A.5.5 0 0 1 12 7.5h3.5a.5.5 0 0 1 0 1h-3.15l-1.88 5.17a.5.5 0 0 1-.94 0L6 3.964 4.47 8.171A.5.5 0 0 1 4 8.5H.5a.5.5 0 0 1 0-1h3.15l1.88-5.17A.5.5 0 0 1 6 2\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"},"color":"#ff5921","size":"40px"} /--></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"animate-aos data-aos_fade-up data-aos-delay_200","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_200" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:sage/icon {"icon":{"name":"bounding-box-circles","iconSet":"sage/bootstrap-icons","source":"\u003csvg fill=\u0022currentColor\u0022 viewBox=\u00220 0 16 16\u0022 height=\u002216\u0022 width=\u002216\u0022 xmlns=\u0022http://www.w3.org/2000/svg\u0022 preserveAspectRatio=\u0022xMidYMid meet\u0022 style=\u0022width:100%;height:100%;\u0022\u003e\u003cpath d=\u0022M2 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2M0 2a2 2 0 0 1 3.937-.5h8.126A2 2 0 1 1 14.5 3.937v8.126a2 2 0 1 1-2.437 2.437H3.937A2 2 0 1 1 1.5 12.063V3.937A2 2 0 0 1 0 2m2.5 1.937v8.126c.703.18 1.256.734 1.437 1.437h8.126a2 2 0 0 1 1.437-1.437V3.937A2 2 0 0 1 12.063 2.5H3.937A2 2 0 0 1 2.5 3.937M14 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2M2 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2m12 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"},"color":"#ff5921","size":"40px"} /--></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"space-between"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"animate-aos data-aos_fade-up data-aos-delay_300","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_300" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:sage/icon {"icon":{"name":"broadcast","iconSet":"sage/bootstrap-icons","source":"\u003csvg fill=\u0022currentColor\u0022 viewBox=\u00220 0 16 16\u0022 height=\u002216\u0022 width=\u002216\u0022 xmlns=\u0022http://www.w3.org/2000/svg\u0022 preserveAspectRatio=\u0022xMidYMid meet\u0022 style=\u0022width:100%;height:100%;\u0022\u003e\u003cpath d=\u0022M3.05 3.05a7 7 0 0 0 0 9.9.5.5 0 0 1-.707.707 8 8 0 0 1 0-11.314.5.5 0 0 1 .707.707m2.122 2.122a4 4 0 0 0 0 5.656.5.5 0 1 1-.708.708 5 5 0 0 1 0-7.072.5.5 0 0 1 .708.708m5.656-.708a.5.5 0 0 1 .708 0 5 5 0 0 1 0 7.072.5.5 0 1 1-.708-.708 4 4 0 0 0 0-5.656.5.5 0 0 1 0-.708m2.122-2.12a.5.5 0 0 1 .707 0 8 8 0 0 1 0 11.313.5.5 0 0 1-.707-.707 7 7 0 0 0 0-9.9.5.5 0 0 1 0-.707zM10 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"},"color":"#ff5921","size":"40px"} /--></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"animate-aos data-aos_fade-up data-aos-delay_400","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_400" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:sage/icon {"icon":{"name":"calendar4-week","iconSet":"sage/bootstrap-icons","source":"\u003csvg fill=\u0022currentColor\u0022 viewBox=\u00220 0 16 16\u0022 height=\u002216\u0022 width=\u002216\u0022 xmlns=\u0022http://www.w3.org/2000/svg\u0022 preserveAspectRatio=\u0022xMidYMid meet\u0022 style=\u0022width:100%;height:100%;\u0022\u003e\u003cpath d=\u0022M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M2 2a1 1 0 0 0-1 1v1h14V3a1 1 0 0 0-1-1zm13 3H1v9a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1z\u0022\u003e\u003c/path\u003e \u003cpath d=\u0022M11 7.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm-2 3a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm-3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5z\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"},"color":"#ff5921","size":"40px"} /--></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center"} -->
<div class="wp-block-column is-vertically-aligned-center"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"space-between"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"animate-aos data-aos_fade-up data-aos-delay_500","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_500" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:sage/icon {"icon":{"name":"easel","iconSet":"sage/bootstrap-icons","source":"\u003csvg fill=\u0022currentColor\u0022 viewBox=\u00220 0 16 16\u0022 height=\u002216\u0022 width=\u002216\u0022 xmlns=\u0022http://www.w3.org/2000/svg\u0022 preserveAspectRatio=\u0022xMidYMid meet\u0022 style=\u0022width:100%;height:100%;\u0022\u003e\u003cpath d=\u0022M8 0a.5.5 0 0 1 .473.337L9.046 2H14a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1h-1.85l1.323 3.837a.5.5 0 1 1-.946.326L11.092 11H8.5v3a.5.5 0 0 1-1 0v-3H4.908l-1.435 4.163a.5.5 0 1 1-.946-.326L3.85 11H2a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h4.954L7.527.337A.5.5 0 0 1 8 0M2 3v7h12V3z\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"},"color":"#ff5921","size":"40px"} /--></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"metadata":{"name":"Services"},"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":285}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:285px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":261}},"className":"animate-aos data-aos_fade-up data-aos-delay_600","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull animate-aos data-aos_fade-up data-aos-delay_600" style="border-radius:0px;min-height:261px;margin-top:0px;margin-bottom:0px;padding-top:0;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"metadata":{"name":"Contents"},"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"var:preset|spacing|40","right":"17px","bottom":"var:preset|spacing|40","left":"17px"},"margin":{"top":"0px","bottom":"0px"}},"dimensions":{"minHeight":250},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","verticalAlignment":"center","justifyContent":"center"}} -->
<div class="wp-block-group alignfull full-width has-background" style="border-radius:0px;background-color:rgba(255,255,255,1);min-height:250px;margin-top:0px;margin-bottom:0px;padding-top:var(--wp--preset--spacing--40);padding-right:17px;padding-bottom:var(--wp--preset--spacing--40);padding-left:17px"><!-- wp:group {"style":{"spacing":{"padding":{"top":"0","bottom":"0"}}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"center"}} -->
<div class="wp-block-group" style="padding-top:0;padding-bottom:0"><!-- wp:group {"metadata":{"name":"Icon Container"},"style":{"spacing":{"padding":{"top":"0","bottom":"0"},"margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"constrained","justifyContent":"center","contentSize":""}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0;padding-top:0;padding-bottom:0"><!-- wp:sage/icon {"icon":{"name":"chat-square-text","iconSet":"sage/bootstrap-icons","source":"\u003csvg fill=\u0022currentColor\u0022 viewBox=\u00220 0 16 16\u0022 height=\u002216\u0022 width=\u002216\u0022 xmlns=\u0022http://www.w3.org/2000/svg\u0022 preserveAspectRatio=\u0022xMidYMid meet\u0022 style=\u0022width:100%;height:100%;\u0022\u003e\u003cpath d=\u0022M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z\u0022\u003e\u003c/path\u003e \u003cpath d=\u0022M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5M3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6m0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5\u0022\u003e\u003c/path\u003e\u003c/svg\u003e"},"color":"#ff5921","size":"40px"} /--></div>
<!-- /wp:group -->

<!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"22px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width text-nowrap has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:22px;font-weight:700;line-height:1.2">Nesciunt Mete</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"14px","fontWeight":"400","lineHeight":"1.7"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:14px;font-weight:400;line-height:1.7">Provident nihil minus qui consequatur non omnis<br>maiores. Eos accusantium minus dolores iure<br>perferendis tempore et consequatur.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></section>
<!-- /wp:group -->