<!-- wp:group {"tagName":"section","metadata":{"name":"Team"},"align":"full","style":{"color":{"background":"rgba(255,88,33,0.03)"},"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"var:preset|spacing|30","right":"0px","bottom":"var:preset|spacing|30","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":660}},"className":"full-width team section","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center","flexWrap":"nowrap"}} -->
<section class="wp-block-group alignfull full-width team section has-background" style="border-radius:0px;background-color:rgba(255,88,33,0.03);min-height:660px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:var(--wp--preset--spacing--30);padding-right:0px;padding-bottom:var(--wp--preset--spacing--30);padding-left:0px"><!-- wp:group {"align":"full","layout":{"type":"constrained","contentSize":"1320px"}} -->
<div class="wp-block-group alignfull"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"15px","padding":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":138}},"className":"","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"center","flexWrap":"nowrap"}} -->
<div class="wp-block-group alignfull" style="border-radius:0px;min-height:138px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":39}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top","flexWrap":"nowrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:39px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"1296px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(71,61,58,1)"},"typography":{"fontSize":"32px","fontWeight":"700","lineHeight":"1.2"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"wp-block-heading full-width has-raleway-font-family"} -->
<h2 class="wp-block-heading has-text-align-center full-width has-raleway-font-family has-text-color" style="color:rgba(71,61,58,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:32px;font-weight:700;line-height:1.2">Team</h2>
<!-- /wp:heading --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":24}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"top","flexWrap":"nowrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:24px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"layout":{"contentSize":"1296px","type":"constrained"}} -->
<div class="wp-block-group" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,1)"},"typography":{"fontSize":"16px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,1);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:16px;font-weight:400;line-height:1.5">Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:columns {"align":"wide","style":{"border":{"radius":"0px"},"spacing":{"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"blockGap":{"top":"0px","left":"0px"}},"className":"full-width","customStyle":{"style":""}}} -->
<div class="wp-block-columns alignwide" style="border-radius:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:column {"verticalAlignment":"center","width":"25%","className":"animate-aos data-aos_fade-up data-aos-delay_100"} -->
<div class="wp-block-column is-vertically-aligned-center animate-aos data-aos_fade-up data-aos-delay_100" style="flex-basis:25%"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"24px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":426}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:426px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:24px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":402}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:402px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"5px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":402}},"className":"team-member","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"space-between"}} -->
<div class="wp-block-group alignfull team-member has-background" style="border-radius:5px;background-color:rgba(255,255,255,1);min-height:402px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"className":"member-img","layout":{"type":"constrained"}} -->
<div class="wp-block-group member-img"><!-- wp:image {"id":48,"aspectRatio":"1","scale":"cover","sizeSlug":"full","linkDestination":"none","style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"blob-image img-fluid"} -->
<figure class="wp-block-image size-full blob-image img-fluid" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><img src="@asset('images/team/team-1.jpg')" alt="" class="wp-image-48" style="aspect-ratio:1;object-fit:cover"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"padding":{"top":"28px","right":"15px","bottom":"28px","left":"15px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"blockGap":"5px"},"dimensions":{"minHeight":116},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","flexWrap":"wrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:116px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:28px;padding-right:15px;padding-bottom:28px;padding-left:15px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(49,48,48,0.8)"},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"700"}},"className":"full-width text-nowrap","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-text-color has-headline-font-family" style="color:rgba(49,48,48,0.8);font-size:18px;font-style:normal;font-weight:700">Walter White</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.6)"},"typography":{"fontSize":"13px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,0.6);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:13px;font-weight:400;line-height:1.5">Chief Executive Officer</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"25%","className":"animate-aos data-aos_fade-up data-aos-delay_100"} -->
<div class="wp-block-column is-vertically-aligned-center animate-aos data-aos_fade-up data-aos-delay_100" style="flex-basis:25%"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"24px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":426}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:426px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:24px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":402}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:402px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"5px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":402}},"className":"team-member","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"space-between"}} -->
<div class="wp-block-group alignfull team-member has-background" style="border-radius:5px;background-color:rgba(255,255,255,1);min-height:402px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"className":"member-img","layout":{"type":"constrained"}} -->
<div class="wp-block-group member-img"><!-- wp:image {"id":48,"aspectRatio":"1","scale":"cover","sizeSlug":"full","linkDestination":"none","style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"blob-image"} -->
<figure class="wp-block-image size-full blob-image" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><img src="@asset('images/team/team-2.jpg')" alt="" class="wp-image-48" style="aspect-ratio:1;object-fit:cover"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"padding":{"top":"28px","right":"15px","bottom":"28px","left":"15px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"blockGap":"5px"},"dimensions":{"minHeight":116},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","flexWrap":"wrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:116px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:28px;padding-right:15px;padding-bottom:28px;padding-left:15px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(49,48,48,0.8)"},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"700"}},"className":"full-width text-nowrap","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-text-color has-headline-font-family" style="color:rgba(49,48,48,0.8);font-size:18px;font-style:normal;font-weight:700">Sarah Jhonson</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.6)"},"typography":{"fontSize":"13px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,0.6);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:13px;font-weight:400;line-height:1.5">Product Manager</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"25%","className":"animate-aos data-aos_fade-up data-aos-delay_100"} -->
<div class="wp-block-column is-vertically-aligned-center animate-aos data-aos_fade-up data-aos-delay_100" style="flex-basis:25%"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"24px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":426}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:426px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:24px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":402}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:402px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"5px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":402}},"className":"team-member","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"space-between"}} -->
<div class="wp-block-group alignfull team-member has-background" style="border-radius:5px;background-color:rgba(255,255,255,1);min-height:402px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"className":"member-img","layout":{"type":"constrained"}} -->
<div class="wp-block-group member-img"><!-- wp:image {"id":48,"aspectRatio":"1","scale":"cover","sizeSlug":"full","linkDestination":"none","style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"blob-image"} -->
<figure class="wp-block-image size-full blob-image" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><img src="@asset('images/team/team-3.jpg')" alt="" class="wp-image-48" style="aspect-ratio:1;object-fit:cover"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"padding":{"top":"28px","right":"15px","bottom":"28px","left":"15px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"blockGap":"5px"},"dimensions":{"minHeight":116},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","flexWrap":"wrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:116px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:28px;padding-right:15px;padding-bottom:28px;padding-left:15px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(49,48,48,0.8)"},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"700"}},"className":"full-width text-nowrap","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-text-color has-headline-font-family" style="color:rgba(49,48,48,0.8);font-size:18px;font-style:normal;font-weight:700">William Anderson</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.6)"},"typography":{"fontSize":"13px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,0.6);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:13px;font-weight:400;line-height:1.5">CTO</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"25%","className":"animate-aos data-aos_fade-up data-aos-delay_100"} -->
<div class="wp-block-column is-vertically-aligned-center animate-aos data-aos_fade-up data-aos-delay_100" style="flex-basis:25%"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"24px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":426}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"left","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:426px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:24px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"12px","bottom":"0px","left":"12px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":402}},"className":"full-width","layout":{"type":"flex","orientation":"horizontal","justifyContent":"center","verticalAlignment":"center"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:402px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:12px;padding-bottom:0px;padding-left:12px"><!-- wp:group {"align":"full","style":{"color":{"background":"rgba(255,255,255,1)"},"border":{"radius":"5px"},"spacing":{"blockGap":"0px","padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}},"dimensions":{"minHeight":402}},"className":"team-member","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","verticalAlignment":"space-between"}} -->
<div class="wp-block-group alignfull team-member has-background" style="border-radius:5px;background-color:rgba(255,255,255,1);min-height:402px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group {"className":"member-img","layout":{"type":"constrained"}} -->
<div class="wp-block-group member-img"><!-- wp:image {"id":48,"aspectRatio":"1","scale":"cover","sizeSlug":"full","linkDestination":"none","style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"className":"blob-image"} -->
<figure class="wp-block-image size-full blob-image" style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px"><img src="@asset('images/team/team-4.jpg')" alt="" class="wp-image-48" style="aspect-ratio:1;object-fit:cover"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:group {"align":"full","style":{"border":{"radius":"0px"},"spacing":{"padding":{"top":"28px","right":"15px","bottom":"28px","left":"15px"},"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"},"blockGap":"5px"},"dimensions":{"minHeight":116},"layout":{"selfStretch":"fit","flexSize":null}},"className":"full-width","layout":{"type":"flex","orientation":"vertical","justifyContent":"center","flexWrap":"wrap"}} -->
<div class="wp-block-group alignfull full-width" style="border-radius:0px;min-height:116px;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:28px;padding-right:15px;padding-bottom:28px;padding-left:15px"><!-- wp:heading {"textAlign":"center","style":{"color":{"text":"rgba(49,48,48,0.8)"},"typography":{"fontSize":"18px","fontStyle":"normal","fontWeight":"700"}},"className":"full-width text-nowrap","fontFamily":"headline"} -->
<h2 class="wp-block-heading has-text-align-center full-width text-nowrap has-text-color has-headline-font-family" style="color:rgba(49,48,48,0.8);font-size:18px;font-style:normal;font-weight:700">Amanda Jepson</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"center","style":{"color":{"text":"rgba(49,48,48,0.6)"},"typography":{"fontSize":"13px","fontWeight":"400","lineHeight":"1.5"},"spacing":{"margin":{"top":"0px","bottom":"0px","right":"0px","left":"0px"}}},"className":"full-width","fontFamily":"Roboto"} -->
<p class="has-text-align-center full-width has-text-color has-roboto-font-family" style="color:rgba(49,48,48,0.6);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;font-size:13px;font-weight:400;line-height:1.5">Accountant</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group --></section>
<!-- /wp:group -->